#pragma once

enum class Surfaces {
	PlayerIdleLeft,
	PlayerIdleRight,
	PlayerWalkLeft,
	PlayerWalkRight,

	PenguinIdleLeft,
	PenguinIdleRight,
	PenguinWalkLeft,
	PenguinWalkRight,

	BlueSlimeIdleLeft,
	BlueSlimeIdleRight,
	BlueSlimeWalkLeft,
	BlueSlimeWalkRight,
	GreenSlimeIdleLeft,
	GreenSlimeIdleRight,
	GreenSlimeWalkLeft,
	GreenSlimeWalkRight,
	IceDragonIdleLeft,
	IceDragonIdleRight,
	IceDragonWalkLeft,
	IceDragonWalkRight,
	WindDragonIdleLeft,
	WindDragonIdleRight,
	WindDragonWalkLeft,
	WindDragonWalkRight,
	EarthDragonIdleLeft,
	EarthDragonIdleRight,
	EarthDragonWalkLeft,
	EarthDragonWalkRight,
	FireDragonIdleLeft,
	FireDragonIdleRight,
	FireDragonWalkLeft,
	FireDragonWalkRight,

	BlueSlime,
	GreenSlime,
	IceGem,
	WindGem,
	EarthGem,
	FireGem,

	SlipperyOrb,
	SlimeTape,
	RainBoots,
	GliderWings,
	StoneWheel,
	RocketBooster,
	StickyOrb,
	BurnCream,
	GrapplingHook,
	ClimbingGloves,
	StickyBomb,
	StormInABottle,
	WindCharge,
	ShipInABottle,
	LightningGem,
	IceScates,
	MuddyBlob,
	ObsidianGem,
	ClayBall,
	MagmaBall,
	FireCharge,

	EmptyCauldron,
	EmptyBurningCauldron,
	FilledCauldron,
	FilledBurningCauldron,
	CauldronCloseupFront,
	CauldronCloseupBack,
	CauldronCloseupFire,
	CauldronCloseupFilled,

	Spoon,
	Blower,

	Sign,

	Floor
};